[package]
name = "steam_url_replacer_discord_bot"
version = "0.1.0"
authors = ["ekuinox <depkey@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.7"
dotenv = "0.15.0"
regex = "0.1"
